Fix User Authentication Issues: Redirect After Signup, Navigation on Login, and Email Validation Error Handling
starvader13/Stock-Market-Portfolio pull request #1
Opened 2024-08-14 11:58 UTC by lightning-sagar

The issue was that when a user signed up, the application should have redirected them to the home page ("/"). Instead, it created the account but required the user to log in again.

Additionally, when clicking the login button on the login page, the application should navigate to the home page. However, it currently fails to navigate and allows the user to sign in again.

To address these problems, I created an atom called userAtom to manage user authentication and navigation more effectively.

2024-10-06 10:49 UTC, starvader13 requested changes

2024-10-06 10:49 UTC, starvader13 commented on backend/db/script.js
> +mongoose.connect(process.env.DATABASE_URL).then(()=>{
`DATABASE_URL` does not define which Database we need to create, it only tells us about the MongoDB Connection String.

You can revert this or concat `databaseName` and `connectionString` and then pass that as an argument to `mongoose.connect`

2024-10-06 10:49 UTC, starvader13 commented on frontend/src/components/Sign/Input.jsx
> +        if (password && password.length < 3) {
The condition and the response do not have the same value.

2024-10-06 10:49 UTC, starvader13 commented on frontend/src/components/Sign/Input.jsx
> +        const emailRegex = /^[^\s@]+@[^\s@]+\.(com|in)$/;
This  method could be moved to a utils folder

2024-10-06 10:49 UTC, starvader13 commented on frontend/src/components/Sign/SignIn.jsx
> +            localStorage.setItem("user-data", response.data.msg);
Why are we setting the user data in our localStorage when we already have its Email access?

Also user-data shouldn't be response message.

2024-10-06 10:49 UTC, starvader13 commented on frontend/src/components/Sign/SignIn.jsx
> +            setUser(response.data.msg);
This is very redundant. Different states are getting set by a similar response

2024-10-06 10:49 UTC, starvader13 commented on frontend/src/components/Sign/SignUp.jsx
> +            setUser(data);
where does this data come from?

2024-10-06 10:49 UTC, starvader13 commented on frontend/src/store/atom.js
> +export const userAtom = atom({
Similarly what is the actual use of this user-data?

2024-10-19 11:00 UTC, lightning-sagar commented on backend/db/script.js
> +mongoose.connect(process.env.DATABASE_URL).then(()=>{
Yes, sir. I was thinking that if a user needs to contribute or fork the repo, they could just paste the DB URL directly into the .env file, which might be easier for some. However, you’re right; concatenating databaseName and connectionString would improve readability as well. will be fixing that.....

2024-10-19 11:06 UTC, lightning-sagar commented on frontend/src/components/Sign/Input.jsx
> +        if (password && password.length < 3) {
Yes, sir, I understand. I will update the condition to check if password.length < 6 to align with the error message. Would that be more appropriate?

2024-10-19 11:50 UTC, lightning-sagar commented on frontend/src/components/Sign/Input.jsx
> +        const emailRegex = /^[^\s@]+@[^\s@]+\.(com|in)$/;
yes sir, I’ll move the validateEmail function to the utils folder for better organization

2024-10-19 12:31 UTC, lightning-sagar commented on frontend/src/components/Sign/SignIn.jsx
> +            localStorage.setItem("user-data", response.data.msg);
Yes sir, I understand your point

2025-12-06 16:23 UTC, closed without merging